# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('job', models.CharField(blank=True, max_length=128, null=True)),
                ('show_id', models.IntegerField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'TaskLog',
                'verbose_name_plural': 'TaskLogs',
            },
        ),
    ]
