# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-17 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20180830_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontblock',
            options={'verbose_name': 'Front Block', 'verbose_name_plural': 'Front Blocks'},
        ),
    ]
