# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='log',
            field=models.CharField(blank=True, max_length=3500, null=True),
        ),
    ]
