# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageterm',
            name='term',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
